name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{matrix.compiler.name}} ${{matrix.asio.name}} ${{matrix.build_type}}
    runs-on: ubuntu-latest
# run in docker until jammy is ubuntu-latest
    container: ubuntu:jammy
    strategy:
      matrix:
        compiler:
          - { name: GCC, CC: gcc, CXX: g++ }
          - { name: Clang, CC: clang, CXX: clang++ }
        asio:
          - { name: asio-boost, pkg: libboost-dev, standalone: OFF }
          - { name: asio-standalone, pkg: libasio-dev, standalone: ON }
        build_type: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt update && apt install --no-install-recommends -yq ${{matrix.asio.pkg}} cmake g++ clang ninja-build
#        sudo apt update && sudo apt install --no-install-recommends -yq ${{matrix.asio.pkg}} ninja-build

    - name: Configure CMake
      env:
        CC: ${{matrix.compiler.CC}}
        CXX: ${{matrix.compiler.CXX}}
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -G Ninja -B ${{github.workspace}}/build \
            -DDBUS_ASIO_STANDALONE=${{matrix.asio.standalone}} \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd ${{github.workspace}}/build; ctest -C ${{matrix.build_type}}
